FROM nginx AS base
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY ["CarShopView/CarShopView.csproj", "."]
RUN dotnet restore "CarShopView.csproj"

COPY ["CarShopView", "."]
RUN dotnet build "CarShopView.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "CarShopView.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM  base AS final
WORKDIR /home
COPY --from=publish /app/publish/wwwroot .