FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build

WORKDIR /app
COPY carshop/CarShop/CarShop.csproj /app/CarShop/CarShop.csproj
RUN dotnet restore CarShop/CarShop.csproj

WORKDIR /app/CarShop
COPY carshop/CarShop /app/CarShop
RUN dotnet build CarShop.csproj -c Release -o /app/build

FROM build as publish
RUN dotnet publish CarShop.csproj -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:6.0
ENV ASPNETCORE_HTTP_PORT=5103
EXPOSE 80
WORKDIR /app
COPY --from=publish /app/publish .

ENTRYPOINT [ "dotnet", "CarShop.dll" ]
