FROM mcr.microsoft.com/dotnet/sdk:6.0 AS base
RUN apt update -y
RUN apt install wget -y
#RUN add-apt-repository ppa:dotnet/backports
# Get OS version info
WORKDIR /app
COPY carshop /app
RUN chmod +x package-script.sh
RUN ./package-script.sh
# RUN apt install software-properties-common -y
# RUN apt-get install dotnet-sdk-6.0 -y



WORKDIR /app/CarShop
CMD ["dotnet", "dev-certs", "https", "--trust"]
# RUN ["dotnet", "restore"]

# #WORKDIR /app

# FROM base as builder

# #COPY carshop .

# CMD ["dotnet", "build", "-c", "-o", "../build"]

# FROM builder as dev-envs

# RUN <<EOF
# apt-get update
# apt-get install -y git
# EOF

# RUN <<EOF
# useradd -s /bin/bash -m vscode
# groupadd docker
# usermod -aG docker vscode
# EOF
# # install Docker tools (cli, buildx, compose)
# COPY --from=gloursdocker/docker / /

CMD ["dotnet", "run"]

# FROM builder AS publisher

# RUN ["dotnet", "publish", "-c", "Release", "-o", "/build"]

# FROM --platform=$BUILDPLATFORM mcr.microsoft.com/dotnet/aspnet:8.0

# WORKDIR /app/CarShop
# COPY --from=publisher /build .

# CMD ["tail", "-f", "/dev/null"]