// <auto-generated />
using System;
using CarShop.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CarShop.Migrations
{
    [DbContext(typeof(CarShopDataContext))]
    partial class CarShopDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CarShop.Models.ClientDB", b =>
                {
                    b.Property<int>("ClientDBId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("client_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ClientDBId"));

                    b.Property<string>("DocNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("doc_number");

                    b.Property<string>("DocType")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)")
                        .HasColumnName("doc_type");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("name");

                    b.Property<string>("PerfilPhoto")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("image_url");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("phonenumber");

                    b.HasKey("ClientDBId");

                    b.ToTable("clients");
                });

            modelBuilder.Entity("CarShop.Models.FinancialTransactionsDB", b =>
                {
                    b.Property<int>("FinancialTransactionDBId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("financial_transation_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("FinancialTransactionDBId"));

                    b.Property<int>("CategoriaId")
                        .HasColumnType("integer")
                        .HasColumnName("categoria_id");

                    b.Property<int?>("ClientDBId")
                        .HasColumnType("integer");

                    b.Property<string>("FinancialTransactionType")
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)")
                        .HasColumnName("type_transation");

                    b.Property<decimal>("Value")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("value");

                    b.HasKey("FinancialTransactionDBId");

                    b.HasIndex("ClientDBId");

                    b.ToTable("financial_transactions");
                });

            modelBuilder.Entity("CarShop.Models.FinancialTransactionsDB", b =>
                {
                    b.HasOne("CarShop.Models.ClientDB", "Client")
                        .WithMany("FinancialTransactions")
                        .HasForeignKey("ClientDBId");

                    b.Navigation("Client");
                });

            modelBuilder.Entity("CarShop.Models.ClientDB", b =>
                {
                    b.Navigation("FinancialTransactions");
                });
#pragma warning restore 612, 618
        }
    }
}
