global using Xunit;
global using CarShop.Context;
global using Moq;
global using CarShop.Controllers;
global using CarShop.Models;
global using System.Collections.Generic;
global using System.Threading.Tasks;
global using System.Linq;
global using System;
